# Default values for planarally.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
## @param 1 [number] Server deployment replica count
replicaCount: 1

image:
  ## @param docker.io [string] Image container registry
  registry: docker.io
  ## @param kruptein/planarally [string] Image repository
  repository: kruptein/planarally
  ## @param IfNotPresent [string] Image pull policy
  pullPolicy: IfNotPresent
  ## @param "" [string] Overrides the image tag whose default is the chart appVersion.
  tag: ""

## @param [] [array] Image pull secrets
imagePullSecrets: []
## @param "" [string] Partial name override
nameOverride: ""
## @param "" [string] Full name override
fullnameOverride: ""

serviceAccount:
  ## @param true [boolean] Specifies whether a service account should be created
  create: true
  ## @param {} [object] Annotations to add to the service account
  annotations: {}
  ## @param "" [string] The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

## @param {} [object] Pod annotations
podAnnotations: {}

## @param {} [object] Pod security context
podSecurityContext: {}
  # fsGroup: 2000
  #
## @param {} [object] Security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  ## @param ClusterIP [string] Service type
  type: ClusterIP

# the first port is specially reserved for HTTP
# and will be picked up by ingress + reverse-proxy
# other ports are useful for in-cluster processes
ports:
  ## @param http [string] Primary port name
- name: http
  ## @param 8000 [number] Primary port of the container
  containerPort: 8000
  ## @param 80 [number] Primary port of the service
  servicePort: 80
  ## @param TCP [string] Primary port protocol
  protocol: TCP

ingress:
  ## @param false [boolean] Enable ingress
  enabled: false
  ## @param "" [string] Ingress class
  className: ""
  ## @param {} [object] Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    ## @param planarally.local [string] Ingress host
    - host: planarally.local
      paths:
        ## @param / [string] Ingress path
        - path: /
          ## @param ImplementationSpecific [string] Ingress path type
          pathType: ImplementationSpecific
  ## @param [] [array] Ingress TLS
  tls: []
  #  - secretName: planarally-tls
  #    hosts:
  #      - planarally.local

## @param {} [object] Resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  ## @param false [boolean] Enable autoscaling
  enabled: false
  ## @param 1 [number] Minimum number of replicas
  minReplicas: 1
  ## @param 3 [number] Maximum number of replicas
  maxReplicas: 3
  ## @param 80 [number] Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## @param {} [object] Node selector
nodeSelector: {}

## @param [] [array] Tolerations
tolerations: []

## @param {} [object] Node affinity
affinity: {}
