name: 'Update README metadata'

#on:
#  pull_request_target:
#    branches:
#      - main
#    paths:
#      - 'charts/*/values.yaml'
on:
  push:
    branches:
      - helm-chart
    #paths:
    #  - 'charts/*/values.yaml'
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute readme-generator-for-helm
        env:
          DIFF_URL: "${{github.event.pull_request.diff_url}}"
          TEMP_FILE: "${{runner.temp}}/pr-${{github.event.number}}.diff"
        run: |
          for chart in "charts/"*
          do
            echo "Updating README.md for ${chart}"
            readme-generator --values "${chart}/values.yaml" --readme "${chart}/README.md" --schema "/tmp/schema.json"
          done
      #- name: Push changes
      #  run: |
      #    # Push all the relevant changes
      #    git add charts/*/README.md
      #    if ! git diff --cached --quiet --exit-code
      #    then
      #      git config user.name "github-actions[bot]"
      #      git config user.email "github-actions[bot]@users.noreply.github.com"
      #      git commit -am "Update README.md with readme-generator-for-helm" --signoff
      #      git push
      #    fi
